### ISSUE TITLE
Intel i219 Issue

### ISSUE THREAD

**Issue by ansash** [AuxXxilium/arc#34]
ARC Loader v 22.12.18 starts and gets a working IP.
After selecting any modell and building the loader the boot afterwards results in an not reachable system - the shown IP is not reachable (target would be 918+).
Rebooting into config mode again, the system is reachable again.

'lsmod' shows 1000e loaded - here is the 'lspci -tvnnq' output:
-[0000:00]-+-00.0  Intel Corporation 10th Gen Core Processor Host Bridge/DRAM Registers [8086:9b63]
           +-02.0  Intel Corporation CometLake-S GT2 [UHD Graphics 630] [8086:9bc8]
           +-14.0  Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller [8086:43ed]
           +-14.2  Intel Corporation Tiger Lake-H Shared SRAM [8086:43ef]
           +-15.0  Intel Corporation Tiger Lake-H Serial IO I2C Controller #0 [8086:43e8]
           +-16.0  Intel Corporation Tiger Lake-H Management Engine Interface [8086:43e0]
           +-17.0  Intel Corporation Device [8086:43d2]
           +-1c.0-[01]--
           +-1d.0-[02]--
           +-1f.0  Intel Corporation Device [8086:4387]
           +-1f.4  Intel Corporation Tiger Lake-H SMBus Controller [8086:43a3]
           +-1f.5  Intel Corporation Tiger Lake-H SPI Controller [8086:43a4]
           \-1f.6  Intel Corporation Ethernet Connection (14) I219-V [8086:15fa]

Board is the ASUS Pro B560M-C.

Other related searches show a mapping problem with the i219-V (appendix).

Any idea or steps I can do to get it working ? Thanks in advance !

**Comment by ansash** [comment]
> 1. i have new intel networm modules in testing.
cool ! you make very fast updates !
>     2. why do you want to use 918? Look at github description.
Its an i3-10100 with FMA, I only have SATA and will use it bare metal. I tested the others models too, however I will use the one which will work finally.
>     3. Log file shows me, that i need to use the new network modules.
Thanks !

**Comment by AuxXxilium** [comment]
You will be better with DS3622xs+ and the new version: v22.12.20 should fix the intel network problem.

**Comment by ansash** [comment]
I tried both 3622 and 918 - problem persists. IP is shortly reachable and fails after booting DSM. Module 1000e is loaded.
Any other idea ? Is the DSM dmesg log saved on the stick somewhere ?

**Comment by AuxXxilium** [comment]
![Screenshot 2022-12-21 204940](https://user-images.githubusercontent.com/67025065/208991143-d6595c56-1c73-4012-b230-d6cd9fc99350.png)

**Comment by AuxXxilium** [comment]
This is right. Your device should use the igb module. try new version after github has build it.
